import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, PhoneOff, Users, Video } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { PathwaayMark } from "@/components/brand";
import { authorizeClassroom } from "@/lib/classroom-video.functions";
import { useCloudflareRealtime } from "@/lib/use-cloudflare-realtime";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/_authenticated/classroom/$classId")({ssr:false,component:Classroom});
type Session={isModerator:boolean;title:string;capacity:number;identity:string;name:string};
function Classroom(){const {classId}=Route.useParams(),nav=useNavigate();const [session,setSession]=useState<Session|null>(null),[authError,setAuthError]=useState<string|null>(null);
 useEffect(()=>{let stopped=false;void(async()=>{try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token){nav({to:"/login",replace:true});return;}const value=await authorizeClassroom({data:{classId,accessToken:token}});if(!stopped)setSession(value);}catch(e){if(!stopped)setAuthError(e instanceof Error?e.message:"Could not join this classroom.");}})();return()=>{stopped=true;};},[classId,nav]);
 const [token,setToken]=useState<string|null>(null);useEffect(()=>{void supabase.auth.getSession().then(({data})=>setToken(data.session?.access_token??null));},[]);
 const live=useCloudflareRealtime({classId:session?classId:null,accessToken:session?token:null,identity:session?.identity??null,name:session?.name??"Student",onDisconnected:()=>nav({to:"/home"})});
 const error=authError??live.error;if(error)return <Failure message={error} removed={live.removed} onHome={()=>nav({to:"/home"})}/>;
 const leave=()=>void live.leave();const total=live.peers.length+1;
 return <div className="flex h-[100dvh] flex-col bg-room text-white"><header className="flex items-center gap-3 border-b border-white/10 px-4 py-3"><button onClick={leave} aria-label="Leave classroom" className="rounded-lg p-2 hover:bg-white/10"><ArrowLeft className="h-5 w-5"/></button><PathwaayMark className="h-8 w-8"/><div className="min-w-0"><p className="truncate text-sm font-semibold">{session?.title??"Classroom"}</p><p className="text-xs text-white/50">{live.status==="connected"?`Live · ${total} people`:"Connecting…"}</p></div><span className="ml-auto flex items-center gap-1 text-xs text-white/60"><Users className="h-4 w-4"/>{total}/{session?.capacity??30}</span></header>
 {live.warningCount>0&&<div role="alert" className="mx-auto mt-3 w-[min(680px,calc(100%-24px))] rounded-lg border border-amber-400/40 bg-amber-500/15 px-4 py-3 text-center text-sm text-amber-100">Your camera must remain ON to stay in this classroom. Warning {live.warningCount} of 3.</div>}
 <main className="min-h-0 flex-1 overflow-y-auto p-3">{!session||live.status==="connecting"?<div className="flex h-full items-center justify-center text-center"><div><PathwaayMark className="mx-auto h-14 w-14 animate-pulse"/><p className="mt-4">Joining your video-only classroom…</p><p className="mt-1 text-sm text-white/50">Allow camera access when your browser asks.</p></div></div>:<div className="grid grid-cols-[repeat(auto-fit,minmax(180px,1fr))] gap-3"><Tile name="You" track={live.localVideo} me/>{live.peers.map(p=><Tile key={p.identity} name={p.name} track={p.video}/>)}</div>}</main>
 <footer className="border-t border-white/10 p-3 text-center"><button onClick={leave} className="inline-flex items-center gap-2 rounded-full bg-danger px-5 py-3 text-sm font-semibold"><PhoneOff className="h-5 w-5"/>Leave classroom</button><p className="mt-2 text-xs text-white/45">This classroom is video-only. Your camera must stay on.</p></footer></div>;}
function Tile({name,track,me}:{name:string;track?:MediaStreamTrack|null;me?:boolean}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current)ref.current.srcObject=track?new MediaStream([track]):null;void ref.current?.play().catch(()=>{});},[track]);return <div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-black/40 ring-1 ring-white/10">{track?<video ref={ref} autoPlay playsInline muted={me} className={cn("h-full w-full object-cover",me&&"scale-x-[-1]")}/>:<div className="flex h-full flex-col items-center justify-center gap-2 text-white/60"><Video className="h-8 w-8"/><span className="text-xs">Connecting video…</span></div>}<span className="absolute bottom-0 inset-x-0 bg-black/50 px-3 py-2 text-xs font-semibold">{name}{me&&" (You)"}</span></div>;}
function Failure({message,removed,onHome}:{message:string;removed:boolean;onHome:()=>void}){return <div className="flex h-[100dvh] items-center justify-center bg-room px-6 text-center text-white"><div><h1 className="text-lg font-bold">{removed?"Removed from classroom":"Couldn't join the classroom"}</h1><p className="mt-2 max-w-sm text-sm text-white/60">{message}</p>{removed&&<p className="mt-2 text-sm text-white/60">Your camera must remain ON to stay in this classroom.</p>}<button onClick={onHome} className="mt-5 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Go home</button></div></div>;}
